[package]
name = "governance_factory"
version = "1.0.0"

[addresses]
admin = "0xe799069a01bcb4e79a714d685a0fa850e644d9b0d973844ad37dd46b543570c9"
governance_factory = "0xe799069a01bcb4e79a714d685a0fa850e644d9b0d973844ad37dd46b543570c9"

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"
